### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by pmorelli92** [toronik/grpc-wiremock#1]
I read on the advent27 issues that you intend to maintain the codebase and I see you already tried to add arm64 support. Are you going to publish those images somewhere?

Thanks!

**Comment by toronik** [comment]
Hi!

arm64 support has been published [1.4.0](https://hub.docker.com/layers/adven27/grpc-wiremock/1.4.0/images/sha256-72bb1d396aee294db0fc38e9710e129560c0ce18444b48cf13a406d02f970d65?context=explore)
